apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  .env: |
    NODE_ENV=dev
    PORT=3000

    DB_HOST=mysql
    DB_PORT=3306
    DB_USERNAME=root
    DB_PASSWORD=
    DB_NAME=quiz_test

    REDIS_HOST=redis
    REDIS_PORT=6379
    REDIS_DB=1
    REDIS_PASSWORD=redis
    REDIS_PREFIX=quiz